---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: '{{ source_url }}/-/tree/{{ revision }}'
    build.appstudio.redhat.com/commit_sha: '{{ revision }}'
    build.appstudio.redhat.com/pull_request_number: '{{ pull_request_number }}'
    build.appstudio.redhat.com/target_branch: '{{ target_branch }}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: hello-world-package-github
    appstudio.openshift.io/component: konflux-test-package-cc7e5
    pipelines.appstudio.openshift.io/type: build
  name: hello-build-on-pull-request
  namespace: centos-stream-integration-test-tenant
spec:
  params:
    - name: ociStorage
      value: quay.io/redhat-user-workloads/centos-stream-integration-test-tenant/konflux-test-package-cc7e5:on-pr-{{ pull_request_number }}-{{revision}}
    - name: package-name
      value: hello
    - name: git-url
      value: "{{ source_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: target-branch
      value: "{{ target_branch }}"
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipeline/build-rpm-package.yaml
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
